apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-microservice
  template:
    metadata:
      labels:
        app: go-microservice
    spec:
      containers:
      - name: go-microservice
        image: yuvakkrishnan/go-microservice:<IMAGE_TAG>
        ports:
        - containerPort: 8080
